import { GalaxyParameters, defaultParameters } from "./parameters";

export interface Preset {
  name: string;
  params: GalaxyParameters;
}

export const presets: Preset[] = [
  { name: "Default", params: { ...defaultParameters } },
  {
    name: "Elliptical (E0-E7)",
    params: {
      starCount: 80000,
      armCount: 1,
      armTwist: 0.6,
      armSpread: 0.95,
      diskRadius: 42,
      verticalThickness: 1.4,
      noise: 0.5,
      coreFalloff: 2.6,
      brightness: 1.3,
      bulgeRadius: 12,
      bulgeStarCount: 70000,
      bulgeFalloff: 1.6,
      bulgeVerticalScale: 1.2,
      bulgeBrightness: 3.2,
    }
  },
  {
    name: "Lenticular (S0)",
    params: {
      starCount: 65000,
      armCount: 2,
      armTwist: 4,
      armSpread: 0.12,
      diskRadius: 45,
      verticalThickness: 0.35,
      noise: 0.1,
      coreFalloff: 2.2,
      brightness: 1.1,
      bulgeRadius: 9,
      bulgeStarCount: 35000,
      bulgeFalloff: 2.1,
      bulgeVerticalScale: 0.8,
      bulgeBrightness: 2.8,
    }
  },
  {
    name: "Spiral (Sa)",
    params: {
      starCount: 80000,
      armCount: 2,
      armTwist: 10,
      armSpread: 0.18,
      diskRadius: 50,
      verticalThickness: 0.45,
      noise: 0.16,
      coreFalloff: 2.4,
      brightness: 1.25,
      bulgeRadius: 8.5,
      bulgeStarCount: 32000,
      bulgeFalloff: 2.4,
      bulgeVerticalScale: 0.9,
      bulgeBrightness: 2.8,
    }
  },
  {
    name: "Spiral (Sb)",
    params: {
      starCount: 78000,
      armCount: 3,
      armTwist: 8.5,
      armSpread: 0.24,
      diskRadius: 52,
      verticalThickness: 0.4,
      noise: 0.2,
      coreFalloff: 2.0,
      brightness: 1.15,
      bulgeRadius: 7,
      bulgeStarCount: 26000,
      bulgeFalloff: 2.2,
      bulgeVerticalScale: 0.8,
      bulgeBrightness: 2.4,
    }
  },
  {
    name: "Spiral (Sc)",
    params: {
      starCount: 76000,
      armCount: 3,
      armTwist: 6.5,
      armSpread: 0.32,
      diskRadius: 54,
      verticalThickness: 0.35,
      noise: 0.22,
      coreFalloff: 1.8,
      brightness: 1.05,
      bulgeRadius: 5,
      bulgeStarCount: 20000,
      bulgeFalloff: 2.0,
      bulgeVerticalScale: 0.7,
      bulgeBrightness: 2.0,
    }
  },
  {
    name: "Spiral (Sd)",
    params: {
      starCount: 70000,
      armCount: 4,
      armTwist: 5,
      armSpread: 0.42,
      diskRadius: 58,
      verticalThickness: 0.4,
      noise: 0.3,
      coreFalloff: 1.4,
      brightness: 0.95,
      bulgeRadius: 3.2,
      bulgeStarCount: 12000,
      bulgeFalloff: 1.6,
      bulgeVerticalScale: 0.6,
      bulgeBrightness: 1.7,
    }
  },
  {
    name: "Barred Spiral (SBa)",
    params: {
      starCount: 82000,
      armCount: 2,
      armTwist: 9,
      armSpread: 0.2,
      diskRadius: 48,
      verticalThickness: 0.45,
      noise: 0.18,
      coreFalloff: 2.0,
      brightness: 1.2,
      bulgeRadius: 9,
      bulgeStarCount: 36000,
      bulgeFalloff: 2.6,
      bulgeVerticalScale: 1.0,
      bulgeBrightness: 3.0,
    }
  },
  {
    name: "Barred Spiral (SBb)",
    params: {
      starCount: 80000,
      armCount: 3,
      armTwist: 7.5,
      armSpread: 0.28,
      diskRadius: 52,
      verticalThickness: 0.42,
      noise: 0.22,
      coreFalloff: 1.9,
      brightness: 1.1,
      bulgeRadius: 7.5,
      bulgeStarCount: 30000,
      bulgeFalloff: 2.2,
      bulgeVerticalScale: 0.9,
      bulgeBrightness: 2.6,
    }
  },
  {
    name: "Barred Spiral (SBc)",
    params: {
      starCount: 78000,
      armCount: 4,
      armTwist: 6,
      armSpread: 0.36,
      diskRadius: 56,
      verticalThickness: 0.38,
      noise: 0.27,
      coreFalloff: 1.6,
      brightness: 1.0,
      bulgeRadius: 5,
      bulgeStarCount: 20000,
      bulgeFalloff: 2.0,
      bulgeVerticalScale: 0.8,
      bulgeBrightness: 2.2,
    }
  },
  {
    name: "Barred Spiral (SBd)",
    params: {
      starCount: 72000,
      armCount: 4,
      armTwist: 4.5,
      armSpread: 0.44,
      diskRadius: 60,
      verticalThickness: 0.42,
      noise: 0.34,
      coreFalloff: 1.3,
      brightness: 0.95,
      bulgeRadius: 3.2,
      bulgeStarCount: 14000,
      bulgeFalloff: 1.7,
      bulgeVerticalScale: 0.7,
      bulgeBrightness: 1.9,
    }
  },
  {
    name: "Irregular (Irr I)",
    params: {
      starCount: 55000,
      armCount: 1,
      armTwist: 1.5,
      armSpread: 0.9,
      diskRadius: 40,
      verticalThickness: 0.9,
      noise: 0.6,
      coreFalloff: 1.0,
      brightness: 0.9,
      bulgeRadius: 2.5,
      bulgeStarCount: 6000,
      bulgeFalloff: 1.2,
      bulgeVerticalScale: 1.1,
      bulgeBrightness: 1.3,
    }
  },
  {
    name: "Irregular (Irr II)",
    params: {
      starCount: 65000,
      armCount: 1,
      armTwist: 0.8,
      armSpread: 1.0,
      diskRadius: 42,
      verticalThickness: 1.1,
      noise: 0.8,
      coreFalloff: 0.9,
      brightness: 0.95,
      bulgeRadius: 2,
      bulgeStarCount: 5000,
      bulgeFalloff: 1.0,
      bulgeVerticalScale: 1.2,
      bulgeBrightness: 1.4,
    }
  },
  {
    name: "Dwarf Elliptical (dE)",
    params: {
      starCount: 12000,
      armCount: 1,
      armTwist: 0.8,
      armSpread: 0.9,
      diskRadius: 16,
      verticalThickness: 0.6,
      noise: 0.35,
      coreFalloff: 2.2,
      brightness: 0.8,
      bulgeRadius: 4,
      bulgeStarCount: 8000,
      bulgeFalloff: 2.2,
      bulgeVerticalScale: 0.9,
      bulgeBrightness: 1.6,
    }
  },
  {
    name: "Dwarf Spheroidal (dSph)",
    params: {
      starCount: 8000,
      armCount: 1,
      armTwist: 0.3,
      armSpread: 0.95,
      diskRadius: 14,
      verticalThickness: 0.9,
      noise: 0.45,
      coreFalloff: 1.6,
      brightness: 0.6,
      bulgeRadius: 3.5,
      bulgeStarCount: 6000,
      bulgeFalloff: 1.4,
      bulgeVerticalScale: 1.0,
      bulgeBrightness: 1.2,
    }
  },
  {
    name: "Dwarf Irregular (dIrr)",
    params: {
      starCount: 10000,
      armCount: 1,
      armTwist: 0.6,
      armSpread: 1.0,
      diskRadius: 18,
      verticalThickness: 1.0,
      noise: 0.75,
      coreFalloff: 1.0,
      brightness: 0.7,
      bulgeRadius: 2.5,
      bulgeStarCount: 4000,
      bulgeFalloff: 1.2,
      bulgeVerticalScale: 1.1,
      bulgeBrightness: 1.1,
    }
  },
  {
    name: "Dwarf Spiral (dSp)",
    params: {
      starCount: 14000,
      armCount: 2,
      armTwist: 4.5,
      armSpread: 0.4,
      diskRadius: 20,
      verticalThickness: 0.35,
      noise: 0.25,
      coreFalloff: 1.7,
      brightness: 0.9,
      bulgeRadius: 3,
      bulgeStarCount: 5000,
      bulgeFalloff: 1.8,
      bulgeVerticalScale: 0.8,
      bulgeBrightness: 1.5,
    }
  },
  {
    name: "Peculiar",
    params: {
      starCount: 70000,
      armCount: 3,
      armTwist: 5.5,
      armSpread: 0.65,
      diskRadius: 48,
      verticalThickness: 0.8,
      noise: 0.6,
      coreFalloff: 1.2,
      brightness: 1.0,
      bulgeRadius: 4,
      bulgeStarCount: 15000,
      bulgeFalloff: 1.4,
      bulgeVerticalScale: 1.1,
      bulgeBrightness: 2.0,
    }
  },
  {
    name: "Shell",
    params: {
      starCount: 50000,
      armCount: 1,
      armTwist: 1.2,
      armSpread: 0.75,
      diskRadius: 70,
      verticalThickness: 1.1,
      noise: 0.5,
      coreFalloff: 1.1,
      brightness: 0.45,
      bulgeRadius: 3,
      bulgeStarCount: 8000,
      bulgeFalloff: 1.5,
      bulgeVerticalScale: 0.9,
      bulgeBrightness: 1.1,
    }
  },
  {
    name: "Ultra-Diffuse",
    params: {
      starCount: 30000,
      armCount: 1,
      armTwist: 2.0,
      armSpread: 0.85,
      diskRadius: 80,
      verticalThickness: 1.3,
      noise: 0.65,
      coreFalloff: 0.8,
      brightness: 0.35,
      bulgeRadius: 2.5,
      bulgeStarCount: 6000,
      bulgeFalloff: 1.3,
      bulgeVerticalScale: 1.2,
      bulgeBrightness: 1.0,
    }
  },
  {
    name: "Seyfert",
    params: {
      starCount: 65000,
      armCount: 2,
      armTwist: 7.0,
      armSpread: 0.26,
      diskRadius: 45,
      verticalThickness: 0.35,
      noise: 0.2,
      coreFalloff: 2.2,
      brightness: 1.3,
      bulgeRadius: 6,
      bulgeStarCount: 26000,
      bulgeFalloff: 2.6,
      bulgeVerticalScale: 0.9,
      bulgeBrightness: 3.5,
    }
  },
  {
    name: "Quasar",
    params: {
      starCount: 60000,
      armCount: 2,
      armTwist: 6,
      armSpread: 0.3,
      diskRadius: 40,
      verticalThickness: 0.6,
      noise: 0.25,
      coreFalloff: 2.4,
      brightness: 2.0,
      bulgeRadius: 5,
      bulgeStarCount: 40000,
      bulgeFalloff: 2.0,
      bulgeVerticalScale: 1.0,
      bulgeBrightness: 6.0,
    }
  },
  {
    name: "Blazar",
    params: {
      starCount: 55000,
      armCount: 2,
      armTwist: 5.5,
      armSpread: 0.32,
      diskRadius: 38,
      verticalThickness: 1.2,
      noise: 0.22,
      coreFalloff: 2.0,
      brightness: 1.8,
      bulgeRadius: 4.5,
      bulgeStarCount: 28000,
      bulgeFalloff: 1.8,
      bulgeVerticalScale: 1.6,
      bulgeBrightness: 5.0,
    }
  },
  {
    name: "Radio Galaxy",
    params: {
      starCount: 85000,
      armCount: 2,
      armTwist: 5.0,
      armSpread: 0.28,
      diskRadius: 60,
      verticalThickness: 0.9,
      noise: 0.2,
      coreFalloff: 1.5,
      brightness: 1.2,
      bulgeRadius: 6.5,
      bulgeStarCount: 24000,
      bulgeFalloff: 1.7,
      bulgeVerticalScale: 1.1,
      bulgeBrightness: 3.2,
    }
  },
  {
    name: "LINER",
    params: {
      starCount: 65000,
      armCount: 2,
      armTwist: 4.5,
      armSpread: 0.3,
      diskRadius: 42,
      verticalThickness: 0.6,
      noise: 0.2,
      coreFalloff: 2.3,
      brightness: 1.0,
      bulgeRadius: 5.5,
      bulgeStarCount: 23000,
      bulgeFalloff: 2.4,
      bulgeVerticalScale: 0.9,
      bulgeBrightness: 2.8,
    }
  },
  {
    name: "Starburst",
    params: {
      starCount: 100000,
      armCount: 3,
      armTwist: 6.5,
      armSpread: 0.48,
      diskRadius: 50,
      verticalThickness: 0.7,
      noise: 0.35,
      coreFalloff: 1.4,
      brightness: 1.6,
      bulgeRadius: 5,
      bulgeStarCount: 32000,
      bulgeFalloff: 1.6,
      bulgeVerticalScale: 1.0,
      bulgeBrightness: 3.5,
    }
  },
  {
    name: "Post-Starburst (E+A / K+A)",
    params: {
      starCount: 65000,
      armCount: 2,
      armTwist: 3.5,
      armSpread: 0.4,
      diskRadius: 48,
      verticalThickness: 0.6,
      noise: 0.3,
      coreFalloff: 1.8,
      brightness: 0.9,
      bulgeRadius: 6.5,
      bulgeStarCount: 28000,
      bulgeFalloff: 2.0,
      bulgeVerticalScale: 1.0,
      bulgeBrightness: 2.2,
    }
  },
  {
    name: "cD Galaxy",
    params: {
      starCount: 130000,
      armCount: 1,
      armTwist: 1.0,
      armSpread: 0.85,
      diskRadius: 90,
      verticalThickness: 1.3,
      noise: 0.55,
      coreFalloff: 1.5,
      brightness: 1.1,
      bulgeRadius: 14,
      bulgeStarCount: 90000,
      bulgeFalloff: 1.3,
      bulgeVerticalScale: 1.2,
      bulgeBrightness: 3.0,
    }
  },
  {
    name: "Brightest Cluster Galaxy (BCG)",
    params: {
      starCount: 115000,
      armCount: 1,
      armTwist: 0.9,
      armSpread: 0.8,
      diskRadius: 85,
      verticalThickness: 1.2,
      noise: 0.5,
      coreFalloff: 1.6,
      brightness: 1.05,
      bulgeRadius: 12,
      bulgeStarCount: 80000,
      bulgeFalloff: 1.4,
      bulgeVerticalScale: 1.1,
      bulgeBrightness: 2.8,
    }
  },
  {
    name: "Flocculent Spiral",
    params: {
      starCount: 72000,
      armCount: 4,
      armTwist: 5.5,
      armSpread: 0.6,
      diskRadius: 48,
      verticalThickness: 0.4,
      noise: 0.5,
      coreFalloff: 1.6,
      brightness: 1.05,
      bulgeRadius: 4.5,
      bulgeStarCount: 16000,
      bulgeFalloff: 1.7,
      bulgeVerticalScale: 0.8,
      bulgeBrightness: 2.0,
    }
  },
  {
    name: "Grand-Design Spiral",
    params: {
      starCount: 90000,
      armCount: 2,
      armTwist: 9.5,
      armSpread: 0.22,
      diskRadius: 55,
      verticalThickness: 0.45,
      noise: 0.2,
      coreFalloff: 2.0,
      brightness: 1.2,
      bulgeRadius: 7,
      bulgeStarCount: 26000,
      bulgeFalloff: 2.3,
      bulgeVerticalScale: 0.9,
      bulgeBrightness: 2.5,
    }
  },
  {
    name: "Anemic Spiral",
    params: {
      starCount: 50000,
      armCount: 2,
      armTwist: 6.5,
      armSpread: 0.3,
      diskRadius: 60,
      verticalThickness: 0.4,
      noise: 0.26,
      coreFalloff: 1.7,
      brightness: 0.7,
      bulgeRadius: 5,
      bulgeStarCount: 14000,
      bulgeFalloff: 1.8,
      bulgeVerticalScale: 0.8,
      bulgeBrightness: 1.6,
    }
  },
  {
    name: "Barred spiral",
    params: {
      starCount: 80000,
      armCount: 2,
      armTwist: 8,
      armSpread: 0.25,
      diskRadius: 50,
      verticalThickness: 0.45,
      noise: 0.2,
      coreFalloff: 1.6,
      brightness: 1.1,
      bulgeRadius: 6,
      bulgeStarCount: 25000,
      bulgeFalloff: 2.2,
      bulgeVerticalScale: 0.9,
      bulgeBrightness: 2.2,
    }
  },
  {
    name: "Compact core",
    params: {
      starCount: 60000,
      armCount: 3,
      armTwist: 6,
      armSpread: 0.3,
      diskRadius: 35,
      verticalThickness: 0.7,
      noise: 0.18,
      coreFalloff: 2.5,
      brightness: 1.2,
      bulgeRadius: 7,
      bulgeStarCount: 30000,
      bulgeFalloff: 2.5,
      bulgeVerticalScale: 0.7,
      bulgeBrightness: 2.5,
    }
  },
  {
    name: "Diffuse arms",
    params: {
      starCount: 70000,
      armCount: 4,
      armTwist: 4.5,
      armSpread: 0.45,
      diskRadius: 55,
      verticalThickness: 0.5,
      noise: 0.35,
      coreFalloff: 1.8,
      brightness: 1.0,
      bulgeRadius: 4,
      bulgeStarCount: 15000,
      bulgeFalloff: 1.8,
      bulgeVerticalScale: 1.0,
      bulgeBrightness: 1.8,
    }
  }
];

export function findPreset(name: string): GalaxyParameters | null {
  const preset = presets.find((p) => p.name === name);
  return preset ? { ...preset.params } : null;
}
