import type { MoonCatalogEntry } from "./types";

export const MOON_CATALOG: Record<string, MoonCatalogEntry> = {
  IO: { key: "IO", displayName: "Io", class: "inner", radiusKm: 1821.6 },
  EUROPA: { key: "EUROPA", displayName: "Europa", class: "inner", radiusKm: 1560.8 },
  GANYMEDE: { key: "GANYMEDE", displayName: "Ganymede", class: "inner", radiusKm: 2634.1 },
  CALLISTO: { key: "CALLISTO", displayName: "Callisto", class: "inner", radiusKm: 2410.3 },
  METIS: { key: "METIS", displayName: "Metis", class: "regular" },
  ADRASTEA: { key: "ADRASTEA", displayName: "Adrastea", class: "regular" },
  AMALTHEA: { key: "AMALTHEA", displayName: "Amalthea", class: "regular" },
  THEBE: { key: "THEBE", displayName: "Thebe", class: "regular" },
  HIMALIA: { key: "HIMALIA", displayName: "Himalia", class: "regular" },
  ELARA: { key: "ELARA", displayName: "Elara", class: "regular" },
  PASIPHAE: { key: "PASIPHAE", displayName: "Pasiphae", class: "regular" },
  SINOPE: { key: "SINOPE", displayName: "Sinope", class: "regular" },
  LYSITHEA: { key: "LYSITHEA", displayName: "Lysithea", class: "regular" },
  CARME: { key: "CARME", displayName: "Carme", class: "regular" },
  ANANKE: { key: "ANANKE", displayName: "Ananke", class: "regular" },
  LEDA: { key: "LEDA", displayName: "Leda", class: "regular" },
  THEMISTO: { key: "THEMISTO", displayName: "Themisto", class: "regular" },
  CALLIRRHOE: { key: "CALLIRRHOE", displayName: "Callirrhoe", class: "irregular" },
  MEGACLITE: { key: "MEGACLITE", displayName: "Megaclite", class: "irregular" },
  TAYGETE: { key: "TAYGETE", displayName: "Taygete", class: "irregular" },
  CHALDENE: { key: "CHALDENE", displayName: "Chaldene", class: "irregular" },
  HARPALYKE: { key: "HARPALYKE", displayName: "Harpalyke", class: "irregular" },
  KALYKE: { key: "KALYKE", displayName: "Kalyke", class: "irregular" },
  IOCASTE: { key: "IOCASTE", displayName: "Iocaste", class: "irregular" },
  ERINOME: { key: "ERINOME", displayName: "Erinome", class: "irregular" },
  ISONOE: { key: "ISONOE", displayName: "Isonoe", class: "irregular" },
  PRAXIDIKE: { key: "PRAXIDIKE", displayName: "Praxidike", class: "irregular" },
  ORTHOSIE: { key: "ORTHOSIE", displayName: "Orthosie", class: "irregular" },
  THYONE: { key: "THYONE", displayName: "Thyone", class: "irregular" },
  KALE: { key: "KALE", displayName: "Kale", class: "irregular" },
  AUTONOE: { key: "AUTONOE", displayName: "Autonoe", class: "irregular" },
  EUKELADE: { key: "EUKELADE", displayName: "Eukelade", class: "irregular" },
  MNEME: { key: "MNEME", displayName: "Mneme", class: "irregular" },
  AEDE: { key: "AEDE", displayName: "Aede", class: "irregular" },
  THELXINOE: { key: "THELXINOE", displayName: "Thelxinoe", class: "irregular" },
  ARCHE: { key: "ARCHE", displayName: "Arche", class: "irregular" },
  "S/2022_J_1": { key: "S/2022_J_1", displayName: "S/2022 J 1", class: "irregular" }
};
